### ISSUE TITLE
Getting user input with study information

### ISSUE THREAD

**Issue by NadzeyaKadakova** [OdyOSG/picard#3]
Q: is it ok to just ask users for a console input? I like your solution with pop-up but seems like its a part of keyring 
@mdlavallee92

**Comment by NadzeyaKadakova** [comment]
Q: do you have ideas on how to use whisker/other package to update only *some* parameters in the markdown file and leave the other ones the way they were? 
I have a problem understanding how to add functionality for project status refreshes after the main readme file is generated

**Comment by mdlavallee92** [comment]
The reason for the prompt was for privacy...you need to put the credential into a pop-up window. With no security at stake, the prompts become too much imo.

Is there a way to pass a list of inputs in whisker, so that people can customize the list? You just need to initialize the readme it doesnt need to be perfect...too many of the inputs dont have a default answer at study start. For instance the project demo...users wont have that at study start. They will have the author, title, a description and a type of study. Keep the inputs minimal or try to find a way to pass a list into whisker for custom bullets in the readme
